<html><head><title>Java Programming/Throwing and Catching Exceptions</title><link media="all" href="../../misc/modern.css" type="text/css" rel="stylesheet"></head><body class="mediawiki"><div id="content"><h1 class="firstHeading" id="firstHeading">Java Programming/Throwing and Catching Exceptions</h1><div id="bodyContent">
								
				
				
								
				
				
																
				
				
								
				<div lang="en" dir="ltr" class="mw-content-ltr">
<p>Language compilers are adept at pointing out most of the erroneous code in a program, however there are some errors that only become apparent when the program is executed. Consider the code in Listing 1.1; here, the program defines a method <b>divide</b> that does a simple division operation taking two integers as parameter arguments and returning the result of their division. It can safely be assumed that when the <b>divide(4, 2)</b> statement is called, it would return the number <b>2</b>. However, consider the next statement, where the program relies upon the provided command line arguments to generate a division operation. What if the user provides the number zero (<b>0</b>) as the second argument. We all know that division by zero is impossible, but the compiler couldn't possibly have anticipated the user providing zero as an argument.</p>
<p><b>Listing 1.1: A simple division operation.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="co1">///: exceptions/ExceptionTutorial01.java</span>
<span class="kw1">public</span> <span class="kw1">class</span> ExceptionTutorial01
<span class="br0">{</span>
  <span class="kw1">public</span> <span class="kw1">static</span> <span class="kw4">int</span> divide<span class="br0">(</span><span class="kw4">int</span> a, <span class="kw4">int</span> b<span class="br0">)</span>
  <span class="br0">{</span>
    <span class="kw1">return</span> a <span class="sy0">/</span> b<span class="sy0">;</span>
  <span class="br0">}</span>
  <span class="kw1">public</span> <span class="kw1">static</span> <span class="kw4">void</span> main<span class="br0">(</span><span class="kw3">String</span><span class="br0">[</span><span class="br0">]</span> args<span class="br0">)</span>
  <span class="br0">{</span>
    <span class="kw3">System</span>.<span class="me1">out</span>.<span class="me1">println</span><span class="br0">(</span> divide<span class="br0">(</span><span class="nu0">4</span>, <span class="nu0">2</span><span class="br0">)</span> <span class="br0">)</span><span class="sy0">;</span>
    <span class="kw1">if</span><span class="br0">(</span>args.<span class="me1">length</span> <span class="sy0">&gt;</span> <span class="nu0">1</span><span class="br0">)</span>
    <span class="br0">{</span>
      <span class="kw4">int</span> arg0 <span class="sy0">=</span> <span class="kw3">Integer</span>.<span class="me1">parseInt</span><span class="br0">(</span>args<span class="br0">[</span><span class="nu0">0</span><span class="br0">]</span><span class="br0">)</span><span class="sy0">;</span>
      <span class="kw4">int</span> arg1 <span class="sy0">=</span> <span class="kw3">Integer</span>.<span class="me1">parseInt</span><span class="br0">(</span>args<span class="br0">[</span><span class="nu0">1</span><span class="br0">]</span><span class="br0">)</span><span class="sy0">;</span>
      <span class="kw3">System</span>.<span class="me1">out</span>.<span class="me1">println</span><span class="br0">(</span> divide<span class="br0">(</span>arg0, arg1<span class="br0">)</span> <span class="br0">)</span><span class="sy0">;</span>
    <span class="br0">}</span>
  <span class="br0">}</span>
<span class="br0">}</span> <span class="coMULTI">/* Output for: java ExceptionTutorial01 1 0
2
Exception in thread "main" java.lang.ArithmeticException: / by zero
     at ExceptionTutorial01.divide(ExceptionTutorial01.java:6)
     at ExceptionTutorial01.main(ExceptionTutorial01.java:15)
*/</span><span class="co1">//:~</span>
</pre></div>
</div>
<p>Such <i>exceptional code</i> that results in erroneous interpretations at program runtime usually results in errors that are called <i>exceptions</i> in Java. When the Java interpreter encounters an exceptional code, it halts execution and displays information about the error that occurs. This information is known as a <b>stack trace</b>. The <b>stack trace</b> in the above example tells us more about the error, such as the thread - <code>"main"</code> - where the exception occurred, the type of exception - <code>java.lang.ArithmeticException</code>, a comprehensible display message - <code>/ by zero</code>, and the exact methods and the line numbers where the exception may have occurred.</p>
<h2> <span class="mw-headline" id="Exception_arguments">Exception arguments</span></h2>
<p>In the code above, the exception object for <code>java.lang.ArithmeticException</code> was generated by the Java interpreter itself. However, there are times when you would need to explicitly create your own exceptions. As with any object in Java, you always create exceptions on the heap using <b>new</b>, which allocates storage and calls a constructor. There are two constructors in all standard exceptions:</p>
<ol><li>The default constructor; and,</li>
<li>A constructor taking a string argument so that you can place pertinent information in the exception.</li>
</ol><p><b>Listing 1.2: Instance of an exception object with the default constructor.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">new</span> <span class="kw3">Exception</span><span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>
</pre></div>
</div>
<p><b>Listing 1.3: Instance of an <code>Exception</code> object by passing string in constructor.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">new</span> <span class="kw3">Exception</span><span class="br0">(</span><span class="st0">"Something unexpected happened"</span><span class="br0">)</span><span class="sy0">;</span>
</pre></div>
</div>
<p>This string can later be extracted using various methods, as you'll see.</p>
<p>The keyword <b>throw</b> produces a number of interesting results. After creating an exception object with <b>new</b>, you give the resulting reference to <b>throw</b>. The object is, in effect, "returned" from the method, even though that object type isn't normally what the method is designed to return. A simplistic way to think about exception handling is as a different kind of return mechanism, although you get into trouble if you take that analogy too far. You can also exit from ordinary scopes by throwing an exception. In either case, an exception object is returned, and the method or scope exits.</p>
<p><b>Listing 1.4: Throwing an exception results in an unexpected return from the method.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">throw</span> <span class="kw1">new</span> <span class="kw3">Exception</span><span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>
</pre></div>
</div>
<p>Anything after the <b>throw</b> statement would not be executed, unless the <i>thrown</i> exception is <a href="http://en.wikibooks.org/w/index.php?title=Java_Programming/Throwing_and_Catching_Exceptions&amp;printable=yes#Exception_handlers">handled</a> properly. Any similarity to an ordinary return from a method ends here, because <i>where</i> you return is some place completely different from where you return for a normal method call, i.e., you end up in an appropriate exception handler that might be far away - many levels on the call stack - from where the exception was thrown.</p>
<p>In addition, you can throw any type of <b>Throwable</b>, which is the exception root class. Typically, you'll throw a different class of exception for each different type of error. The information about therror is represented both inside the exception object and implicitly in the name of the exception class, so someone in the bigger context can figure out what to do with your exception. Often, the only information is the type of exception, and nothing meaningful is stored within the exception object.</p>
<h2> <span class="mw-headline" id="Catching_an_exception">Catching an exception</span></h2>
<p>To see how an exception is caught, you must first understand the concept of a <i>guarded region</i>. This is a section of code that might produce exceptions and is followed by the code to handle those exceptions.</p>
<h3> <span class="mw-headline" id="The_try_block">The <code>try</code> block</span></h3>
<p>If you are inside a method and you throw an exception (or another method that you call within this method throws an exception), that method will exit in the process of throwing. If you don't want a <b>throw</b> to exit the method, you can set up a special block within that method to capture the exception. This is called the <i>try block</i> because you "try" your various method calls there. The <b>try</b> block is an ordinary scope preceded by the keyword <b>try</b>.</p>
<p><b>Listing 1.5: A basic try block.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="co1">// Code that might generate exceptions</span>
<span class="br0">}</span>
</pre></div>
</div>
<p>If you were checking for errors carefully in a programming language that didn't support exception handling, you'd have to surround every method call with setup and error-testing code, even if you call the same method several times. With exception handling, you put everything in a <b>try</b> block and capture all the exceptions in one place. This means your code is much easier to write and read because the goal of the code is not confused with the error checking.</p>
<h2> <span class="mw-headline" id="Exception_handlers">Exception handlers</span></h2>
<p>Of course, the thrown exception must end up some place. This "place" is the <i>exception handler</i>, and there's one for every exception type you want to catch. Exception handlers immediately follow the <b>try</b> block and are denoted by the keyword <b>catch</b>:</p>
<p><b>Listing 1.6: Exception handling with catch blocks.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="co1">// Suppose the code here throws two exceptions:</span>
  <span class="co1">// NullPointerException and NumberFormatException,</span>
  <span class="co1">// then each is handled in a separate catch block.</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">NullPointerException</span> ex<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// Exception handling code for the NullPointerException</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">NumberFormatException</span> ex<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// Exception handling code for the NumberFormatException</span>
<span class="br0">}</span>
<span class="co1">// etc...</span>
</pre></div>
</div>
<p>Using the syntax in Listing 1.6, we can write the potentially problematic division code in Listing 1.1 as under.</p>
<p><b>Listing 1.7: Catching 'division by zero' errors.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw4">int</span> result <span class="sy0">=</span> <span class="nu0">0</span><span class="sy0">;</span>
<span class="kw1">try</span>
<span class="br0">{</span>
  result <span class="sy0">=</span> a <span class="sy0">/</span> b<span class="sy0">;</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">ArithmeticException</span> ex<span class="br0">)</span>
<span class="br0">{</span>
  result <span class="sy0">=</span> <span class="nu0">0</span><span class="sy0">;</span>
<span class="br0">}</span>
<span class="kw1">return</span> result<span class="sy0">;</span>
</pre></div>
</div>
<p>Using the code in Listing 1.7, the program would now not abruptly terminate but continue its execution whilst returning zero for a division by zero operation. I know it's not the correct answer, but hey, it saved your program from terminating abnormally.</p>
<h2> <span class="mw-headline" id="Exception_classes_in_the_JCL">Exception classes in the JCL</span></h2>
<p>The box 1.1 below talks about the various exception classes within the <code>java.lang</code> package of the JCL.</p>
<table style="border:solid 1px #2a7fff; background-color:#fdfdfd;"><tr><td style="padding:8px;">
<p><b>Box 1.1: The Java exception classes</b></p>
<dl><dt>Throwable&#160;</dt>
<dd>The Throwable class is the superclass of all errors and exceptions in the Java language. Only objects that are instances of this class (or one of its subclasses) are thrown by the Java Virtual Machine or can be thrown by the Java throw statement.</dd>
<dd>A throwable contains a snapshot of the execution stack of its thread at the time it was created. It can also contain a message string that gives more information about the error. Finally, it can contain a cause: another throwable that caused this throwable to get thrown. The cause facility is new in release 1.4. It is also known as the chained exception facility, as the cause can, itself, have a cause, and so on, leading to a "chain" of exceptions, each caused by another</dd>
<dt>Error&#160;</dt>
<dd>An Error indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions.</dd>
<dt>Exception&#160;</dt>
<dd>The class Exception and its subclasses are a form of Throwable that indicates conditions that a reasonable application might want to catch. Also this is the class that a programmer may want to extend when adding business logic exceptions.</dd>
<dt>RuntimeException&#160;</dt>
<dd>RuntimeException is the superclass of those exceptions that can be thrown during the normal operation of the Java Virtual Machine. A method is not required to declare in its throws clause any subclasses of RuntimeException that might be thrown during the execution of the method but not caught.</dd>
</dl></td>
<td style="padding:8px;">
<div class="center">
<div class="floatnone"><a href="http://en.wikibooks.org/wiki/File:Java_exception_classes.svg" class="image"><img alt="Java exception classes.svg" src="../../thumbs/74738_339px-Java_exception_classes.svg.png" width="339" height="226"></a></div>
</div>
<br><p><b>Figure 1.1: The exception classes and their inheritance model in the JCL.</b></p>
</td>
</tr></table><h2> <span class="mw-headline" id="Catch_clauses">Catch clauses</span></h2>
<p>There are three distinct types of catch clauses used by Java programmers. We have already explored the first rule in the code listings above. Given below are all three clauses; we will explain all three in greater detail in the next sections.</p>
<ol><li>The <i>catch-list</i> clause</li>
<li>The <i>catch-any</i> clause</li>
<li>The <i>multi-catch</i> clause</li>
</ol><h3> <span class="mw-headline" id="The_catch-list_clause">The <i>catch-list</i> clause</span></h3>
<p>Using the <b>catch-list</b> clause, you provide one handle for every one type of exception. So, for instance if a <i>guarded block</i> generates a <b>NullPointerException</b> and an <b>ArithmeticException</b>, you have two provide two exception handling <b>catch blocks</b> - one for each exception. Refer to code listing 1.6 for an example.</p>
<h3> <span class="mw-headline" id="The_catch-any_clause">The <i>catch-any</i> clause</span></h3>
<p>There are times when too many blocks are just verbose, especially when all exceptions are handled in a similar manner. What you need here is a <b>catch-any</b> clause, where all exceptions are handled in a single <b>catch block</b>. Because all exceptions in Java are the sub-class of <code>java.lang.Exception</code> class, you can have a single <b>catch block</b> that catches an exception of type <b>Exception</b> only. Hence the compiler is fooled into thinking that this block can handle any exception. Using this, the code in Listing 1.6 can be rewritten as follows:</p>
<p><b>Listing 1.8: The catch-any clause.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="co1">// ...</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">Exception</span> ex<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// Exception handling code for ANY exception</span>
<span class="br0">}</span>
</pre></div>
</div>
<h3> <span class="mw-headline" id="The_multi-catch_clause">The <i>multi-catch</i> clause</span></h3>
<p>As of JDK 7, Java added another convenient feature in their exception handling routines - the <b>multi-catch</b> clause. This is a combination of the previous two <b>catch</b> clauses and let's you handle exceptions in a single handler while also maintaining their types. So, instead of being boxed into a parent Exception super-class, they retain their individual types.</p>
<p><b>Listing 1.9: The multi-catch clause.</b></p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="co1">// ...</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">NullPointerException</span> <span class="sy0">|</span> <span class="kw3">NumberFormatException</span> ex<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// Exception handling code specifically for the NullPointerException</span>
  <span class="co1">// and the NumberFormatException</span>
<span class="br0">}</span>
</pre></div>
</div>
<h2> <span class="mw-headline" id="Example_of_handling_exceptions">Example of handling exceptions</span></h2>
<p>Let's examine the following code:</p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">public</span> <span class="kw4">void</span> methodA<span class="br0">(</span><span class="br0">)</span> <span class="kw1">throws</span> SomeException, AnotherException 
<span class="br0">{</span>
    <span class="co1">//methodbody</span>
<span class="br0">}</span>
<span class="kw1">public</span> <span class="kw4">void</span> methodB<span class="br0">(</span><span class="br0">)</span> <span class="kw1">throws</span> CustomException
<span class="br0">{</span>
    <span class="co1">//Methodbody</span>
<span class="br0">}</span>
<span class="kw1">public</span> <span class="kw4">void</span> methodC<span class="br0">(</span><span class="br0">)</span>
<span class="br0">{</span>
    methodB<span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>
    methodA<span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>
<span class="br0">}</span>
</pre></div>
</div>
<p>In the code sample, methodC is invalid. Because methodA and methodB pass (or throw) exceptions, methodC must be prepared to handle them. This can be handled in two ways: a <code><a href="Keywords/try.html" title="Java Programming/Keywords/try"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">try</font></a></code> - <code><a href="Keywords/catch.html" title="Java Programming/Keywords/catch"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">catch</font></a></code> block, which will handle the exception within the method and a <code><a href="Keywords/throws.html" title="Java Programming/Keywords/throws"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">throws</font></a></code> clause which would in turn throw the exception to the caller to handle. The above example will cause a compilation error, as Java is very strict about exception handling. So the programmer forced to handle any possible error condition at some point.</p>
<p>A method can do two things with an exception. Ask the calling method to handle it by the <code><a href="Keywords/throws.html" title="Java Programming/Keywords/throws"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">throws</font></a></code> declaration. Or handle the exception inside the method by the <code><a href="Keywords/try.html" title="Java Programming/Keywords/try"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">try</font></a></code>-<code><a href="Keywords/catch.html" title="Java Programming/Keywords/catch"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">catch</font></a></code> block.</p>
<p>To construct a throws declaration, add <code>throws ExceptionName</code> (additional exceptions can be added with commas). To construct a <code><a href="Keywords/try.html" title="Java Programming/Keywords/try"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">try</font></a></code> - <code><a href="Keywords/catch.html" title="Java Programming/Keywords/catch"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">catch</font></a></code> block, use the following syntax</p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="co1">// Guarded region that will catch any exception that</span>
  <span class="co1">// occurs within this code.</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">Exception</span> ex<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// Caught exceptions are handled here</span>
<span class="br0">}</span>
<span class="kw1">finally</span>
<span class="br0">{</span>
  <span class="co1">// This class is optional. Code here is executed </span>
  <span class="co1">// regardless of exceptions being thrown</span>
<span class="br0">}</span>
</pre></div>
</div>
<p>The original code can be modified to work correctly in multiple ways. For example, the following:</p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">public</span> <span class="kw4">void</span> methodC<span class="br0">(</span><span class="br0">)</span> <span class="kw1">throws</span> CustomException, SomeException
<span class="br0">{</span>
  <span class="kw1">try</span>
  <span class="br0">{</span>
    methodB<span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>
  <span class="br0">}</span>
  <span class="kw1">catch</span><span class="br0">(</span>AnotherException e<span class="br0">)</span>
  <span class="br0">{</span>
    <span class="co1">// Handle caught exceptions.</span>
  <span class="br0">}</span>
  methodA<span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>
<span class="br0">}</span>
</pre></div>
</div>
<p>The AnotherException from methodB will be handled locally, while CustomException and SomeException will be thrown to the caller to handle it.</p>
<h2> <span class="mw-headline" id="Application_Exceptions">Application Exceptions</span></h2>
<p>Application Exception classes should extend the <code>java.lang.Exception</code> class. Some of the JDK classes also throw exception objects inherited from <code>java.lang.Exception</code>. If any of those Exception object is thrown, <b>it must be caught by the application</b> some point, by a catch-block. The compiler will enforce that there is a catch-block associated with an exception thrown, if the thrown exception object is inherited from <code>java.lang.Exception</code> and it is not the <code>java.lang.RuntimeException</code> or its inherited objects. However, <code>java.lang.RuntimeException</code> or its inherited objects, can be caught by the application, but that is not enforced by the compiler.</p>
<p>Lets see what is the catching criteria for a catch block to catch the "thrown" exception.</p>
<p>A catch-block will "catch" a thrown exception if and only if:</p>
<ul><li>the thrown exception object is the same as the exception object specified by the catch-block</li>
<li>the thrown exception object is the subtype of the exception object specified by the catch-block</li>
</ul><div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="kw1">throw</span> <span class="kw1">new</span> <span class="kw3">Exception</span><span class="br0">(</span><span class="st0">"This will be caught below"</span><span class="br0">)</span><span class="sy0">;</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">Exception</span> ex<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// The "thrown" object is the same what is specified at the catch-block</span>
<span class="br0">}</span>
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="kw1">throw</span> <span class="kw1">new</span> <span class="kw3">NullPointerException</span><span class="br0">(</span><span class="st0">"This will be caught below"</span><span class="br0">)</span><span class="sy0">;</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">Exception</span> e<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// NullPointerException is subclass of the Exception class.</span>
<span class="br0">}</span>
</pre></div>
</div>
<p>There can be more than one catch-block for a try-block. The catching blocks evaluated sequentially one by one. If a catch-block catch the exception, the others will not be evaluated.</p>
<p>Example:</p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="kw1">throw</span> <span class="kw1">new</span> <span class="kw3">NullPointerException</span><span class="br0">(</span><span class="st0">"This will be caught below"</span><span class="br0">)</span><span class="sy0">;</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">Exception</span> e<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// The NullPointerException thrown in the code above is caught here...</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">NullPointerException</span> e<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// ..while this code is never executed and the compiler returns an error</span>
<span class="br0">}</span>
</pre></div>
</div>
<p>Because NullPointerException is subclass of the Exception class. All NullPointerExceptions will be caught by the first catch-block.</p>
<p>Instead the above code should be rewritten as follows:</p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">try</span>
<span class="br0">{</span>
  <span class="kw1">throw</span> <span class="kw1">new</span> <span class="kw3">NullPointerException</span><span class="br0">(</span><span class="st0">"This will be caught below"</span><span class="br0">)</span><span class="sy0">;</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">NullPointerException</span> e<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// The above NullPointerException will be caught here...</span>
<span class="br0">}</span>
<span class="kw1">catch</span><span class="br0">(</span><span class="kw3">Exception</span> e<span class="br0">)</span>
<span class="br0">{</span>
  <span class="co1">// ..while other exception are caught here.</span>
<span class="br0">}</span>
</pre></div>
</div>
<h2> <span class="mw-headline" id="Runtime_Exceptions">Runtime Exceptions</span></h2>
<p>The <code>java.lang.RuntimeException</code> exception class is inherited from <code>java.lang.Exception</code>. It is a special exception class, because catching this exception class or its subclasses are not enforced by the Java compiler.</p>
<dl><dt>runtime exception&#160;</dt>
<dd>Runtime exceptions are usually caused by data errors, like arithmetic overflow, divide by zero, ... . Runtime exceptions are not business related exceptions. In a well debugged code, runtime exceptions should not occur. Runtime exceptions should only be used in the case that the exception could be thrown by and only by something hard-coded into the program. These should not be able to be triggered by the software's user(s).</dd>
</dl><h3> <span class="mw-headline" id="NullPointerException">NullPointerException</span></h3>
<p>NullPointerException is a RuntimeException. In Java, a special <code><a href="Literals/null.html" title="Java Programming/Literals/null"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">null</font></a></code> can be assigned to an object reference. NullPointerException is thrown when an application attempts to use an object reference, having the <code><a href="Literals/null.html" title="Java Programming/Literals/null"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">null</font></a></code> value. These include:</p>
<ul><li>Calling an instance method on the object referred by a null reference.</li>
<li>Accessing or modifying an instance field of the object referred by a null reference.</li>
<li>If the reference type is an array type, taking the length of a null reference.</li>
<li>If the reference type is an array type, accessing or modifying the slots of a null reference.</li>
<li>If the reference type is a subtype of Throwable, throwing a null reference.</li>
</ul><p>Applications should throw instances of this class to indicate other illegal uses of the null object.</p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw3">Object</span> obj <span class="sy0">=</span> <span class="kw2">null</span><span class="sy0">;</span>
obj.<span class="me1">toString</span><span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>  <span class="co1">// This statement will throw a NullPointerException</span>
</pre></div>
</div>
<p>The above code shows one of the pitfall of Java, and the most common source of bugs. No object is created and the compiler does not detect it. NullPointerException is one of the most common exceptions thrown in Java.</p>
<h3> <span class="mw-headline" id="Why_do_we_need_null.3F">Why do we need <code>null</code>?</span></h3>
<p>The reason we need it is because many times we need to create an object reference, before the object itself is created. Object references cannot exist without a value, so we assign the <code><a href="Literals/null.html" title="Java Programming/Literals/null"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">null</font></a></code> value to it.</p>
<div dir="ltr" class="mw-geshi" style="text-align: left;">
<div class="java source-java">
<pre class="de1">
<span class="kw1">public</span> Customer getCustomer<span class="br0">(</span><span class="br0">)</span>
<span class="br0">{</span>
  Customer customer <span class="sy0">=</span> <span class="kw2">null</span><span class="sy0">;</span>
  <span class="kw1">try</span>
  <span class="br0">{</span>
    ...
    <span class="me1">customer</span> <span class="sy0">=</span> createCustomer<span class="br0">(</span><span class="br0">)</span><span class="sy0">;</span>
    ...
  <span class="br0">}</span>
  <span class="kw1">catch</span><span class="br0">(</span><span class="kw3">Exception</span> ex<span class="br0">)</span>
  <span class="br0">{</span>
    ...
  <span class="br0">}</span>
  <span class="kw1">return</span> customer<span class="sy0">;</span>
<span class="br0">}</span>
</pre></div>
</div>
<p>In the above code we want to create the Customer inside the try-block, but we also want to return the object reference to the caller, so we need to create the object reference outside of the try-block, because of the scoping rule in Java. This is one of the pitfall of Java.</p>
<h2> <span class="mw-headline" id="Keyword_references">Keyword references</span></h2>
<ul><li><code><a href="Keywords/try.html" title="Java Programming/Keywords/try">try</a></code></li>
<li><code><a href="Keywords/catch.html" title="Java Programming/Keywords/catch">catch</a></code></li>
<li><code><a href="Keywords/throws.html" title="Java Programming/Keywords/throws">throws</a></code></li>
<li><code><a href="Keywords/throw.html" title="Java Programming/Keywords/throw">throw</a></code></li>
</ul>





</div>				
								
				
				
												
								
												
				
				
								<div class="visualClear"></div>
				
								
			</div>
			</div></body></html>